### ISSUE TITLE
Invalid time value in Firefox

### ISSUE THREAD

**Issue by gjj** [Open-Attestation/govtech-decentralized-renderer#6]
@izy100 raised an issue that the [sample cert](https://dev.opencerts.io/?q=%7B%22type%22:%22DOCUMENT%22,%22payload%22:%7B%22uri%22:%22https://gist.githubusercontent.com/gjj/424c690292c3dde10da3472c3fe92727/raw/e1cd29b16387ffa6b6e5652f82ec083a680f2fae/Document-1-Ruijie-Chow.tt%22,%22permittedActions%22:%5B%22STORE%22%5D,%22redirect%22:%22https://opencerts.io%22%7D%7D) does not render properly on Firefox. This was the error:

> Uncaught (in promise) RangeError: Invalid time value

After investigating, turns out Firefox parses `Date` values a little bit differently. Let's take a look using [Mozilla's JS demo](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date).

Here's how `Date("1-Dec-20")` would look like in Firefox (it would be invalid):
![image](https://user-images.githubusercontent.com/506667/94129152-99a82980-fe8d-11ea-8dae-da2dd5189acb.png)

For Chrome, Safari and Edge, `Date("1-Dec-20")` evaluates properly though:
![image](https://user-images.githubusercontent.com/506667/94129041-73828980-fe8d-11ea-8946-aeaf6332ffd9.png)

### What we found out

As it turns out, the [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#Timestamp_string) had this notice:

> **Note:** Parsing of date strings with the `Date` constructor (and `Date.parse()`, which works the same way) is strongly discouraged due to browser differences and inconsistencies.
> - Support for RFC 2822 format strings is by convention only.
> - Support for ISO 8601 formats differs in that date-only strings (e.g. "`1970-01-01`") are treated as UTC, not local.

### To do

So, it means that we shouldn't be using `Date` to attempt to parse different date strings. Will be fixing this in a later MR.

**Comment by dhemutton** [comment]
Tried [this](https://stackoverflow.com/a/21984717) and it works! Let me know how it is for u😊

**Comment by Nebulis** [comment]
I tried `new Date("1994-11-05")` and it works correctly on firefox. So why is this a problem in geekout considering we follow iso 8601 ? Also intern cert should follow the same format :)

**Comment by dhemutton** [comment]
I think because the intern certs dates are being imported from excel in the format "1-Dec-20" so there's an issue in firefox but i think applying regex should solve it!

**Comment by Nebulis** [comment]
I'm talking sur geekout, is geekout find? Also for internship we should use the same format

**Comment by gjj** [comment]
@Nebulis for Intern cert the reason is cos the exported Excel file would be in the format `1-Dec-2020`

If we want ISO 8601, it means that either:

1. we get HR to set it to ISO 8601 already, or
1. our Document Creator to parse it?

**Comment by Nebulis** [comment]
Document creator parse it. Great no issue anymore sorry I didn't notice the pattern used before.
